project_id = "sveaehifwnoetwfxkasn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54329
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://nordata.ai"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_nonce = true

[edge_runtime]
enabled = true
port = 54330

[functions.process-file]
verify_jwt = true

[functions.handle-databricks-callback]
verify_jwt = false

[functions.admin-invite-user]
verify_jwt = true

[functions.chatbot]
verify_jwt = true