
project_id = "sveaehifwnoetwfxkasn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://nordataplatform.vercel.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
s3_max_limit_mb = 100

[edge_functions]
enabled = true

[analytics]
enabled = false

[functions.master-auth]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.admin-get-users]
verify_jwt = true

[functions.admin-invite-user]
verify_jwt = true

[functions.process-file]
verify_jwt = true

[functions.check-job-status]
verify_jwt = true

[functions.handle-databricks-callback]
verify_jwt = false

[functions.chatbot]
verify_jwt = true

[functions.setup-master-user]
verify_jwt = false
