// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sveaehifwnoetwfxkasn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2ZWFlaGlmd25vZXR3ZnhrYXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDAyMDcsImV4cCI6MjA2OTA3NjIwN30.RnCw56Mxy5YdQ12LXl-nKdvgldAVtlErwjj_E15IRmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});